// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRcLhNosrlSKXIAneFHDyQx0pAeVHWWA',
    appId: '1:131897901103:web:526711537d5c52038ac6da',
    messagingSenderId: '131897901103',
    projectId: 'al-khalifa-food-app-ccc7f',
    authDomain: 'al-khalifa-food-app-ccc7f.firebaseapp.com',
    storageBucket: 'al-khalifa-food-app-ccc7f.firebasestorage.app',
    measurementId: 'G-3PRQSFW494',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmz9kyHWXWvCzbSy1tCvzmK99WBeiZ8qk',
    appId: '1:131897901103:android:87049eae453277528ac6da',
    messagingSenderId: '131897901103',
    projectId: 'al-khalifa-food-app-ccc7f',
    storageBucket: 'al-khalifa-food-app-ccc7f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QYYLvwZh1Pcloe-Bb_bXAuYybNE9InY',
    appId: '1:131897901103:ios:ac4fdb6d9464fff98ac6da',
    messagingSenderId: '131897901103',
    projectId: 'al-khalifa-food-app-ccc7f',
    storageBucket: 'al-khalifa-food-app-ccc7f.firebasestorage.app',
    iosBundleId: 'com.example.akflutterfoodapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QYYLvwZh1Pcloe-Bb_bXAuYybNE9InY',
    appId: '1:131897901103:ios:ac4fdb6d9464fff98ac6da',
    messagingSenderId: '131897901103',
    projectId: 'al-khalifa-food-app-ccc7f',
    storageBucket: 'al-khalifa-food-app-ccc7f.firebasestorage.app',
    iosBundleId: 'com.example.akflutterfoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRcLhNosrlSKXIAneFHDyQx0pAeVHWWA',
    appId: '1:131897901103:web:b42932bcb9cc6f3f8ac6da',
    messagingSenderId: '131897901103',
    projectId: 'al-khalifa-food-app-ccc7f',
    authDomain: 'al-khalifa-food-app-ccc7f.firebaseapp.com',
    storageBucket: 'al-khalifa-food-app-ccc7f.firebasestorage.app',
    measurementId: 'G-H8PE1Q9VSB',
  );
}
